### ISSUE TITLE
May be causing ardour to segfault when using pipewire-jack

### ISSUE THREAD

**Issue by michaellass** [michaellass/ladspa-notch-harmonics#4]
Creating a new project in ardour, set to connect to JACK while jack is provided by pipewire-jack and ladspa-notch-harmonics is installed:

```
Jan 13 18:25:17 zenpad systemd-coredump[5454]: Process 5297 (ArdourGUI) of user 1000 dumped core.
                                               
                                               Stack trace of thread 5297:
                                               #0  0x00007fd83c069158 init (notch_harmonics_5761.so + 0x1158)
                                               #1  0x00007fd847642cee n/a (ld-linux-x86-64.so.2 + 0x4cee)
                                               #2  0x00007fd847642ddc n/a (ld-linux-x86-64.so.2 + 0x4ddc)
                                               #3  0x00007fd844b86e94 _dl_catch_exception (libc.so.6 + 0x14fe94)
                                               #4  0x00007fd847649557 n/a (ld-linux-x86-64.so.2 + 0xb557)
                                               #5  0x00007fd844b86e3e _dl_catch_exception (libc.so.6 + 0x14fe3e)
                                               #6  0x00007fd8476498ed n/a (ld-linux-x86-64.so.2 + 0xb8ed)
                                               #7  0x00007fd844ab99dc n/a (libc.so.6 + 0x829dc)
                                               #8  0x00007fd844b86e3e _dl_catch_exception (libc.so.6 + 0x14fe3e)
                                               #9  0x00007fd844b86ef3 _dl_catch_error (libc.so.6 + 0x14fef3)
                                               #10 0x00007fd844ab94af n/a (libc.so.6 + 0x824af)
                                               #11 0x00007fd844ab9a91 dlopen (libc.so.6 + 0x82a91)
                                               #12 0x00007fd845a4e782 g_module_open_full (libgmodule-2.0.so.0 + 0x2782)
                                               #13 0x00007fd8465b3434 _ZN4Glib6ModuleC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_11ModuleFlagsE (libglibmm-2.4.so.1 + 0x43434)
                                               #14 0x00007fd8470cae97 _ZN6ARDOUR13PluginManager15ladspa_discoverENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (libardour.so.3 + 0x6cae97)
                                               #15 0x00007fd8470cc3f6 _ZN6ARDOUR13PluginManager14ladspa_refreshEv (libardour.so.3 + 0x6cc3f6)
                                               #16 0x00007fd8470cc738 _ZN6ARDOUR13PluginManager7refreshEb (libardour.so.3 + 0x6cc738)
                                               #17 0x0000558eb9b1752a n/a (ardour-7.2.0 + 0xba152a)
                                               #18 0x00007fd845878e79 n/a (libgtkmm-2.4.so.1 + 0x278e79)
                                               #19 0x00007fd846523210 g_closure_invoke (libgobject-2.0.so.0 + 0x14210)
                                               #20 0x00007fd846551176 n/a (libgobject-2.0.so.0 + 0x42176)
                                               #21 0x00007fd846540f75 g_signal_emit_valist (libgobject-2.0.so.0 + 0x31f75)
                                               #22 0x00007fd846541204 g_signal_emit (libgobject-2.0.so.0 + 0x32204)
                                               #23 0x00007fd8465cb8cd _ZN4Glib17SignalProxyNormal19slot0_void_callbackEP8_GObjectPv (libglibmm-2.4.so.1 + 0x5b8cd)
                                               #24 0x00007fd846523210 g_closure_invoke (libgobject-2.0.so.0 + 0x14210)
                                               #25 0x00007fd846551176 n/a (libgobject-2.0.so.0 + 0x42176)
                                               #26 0x00007fd846540f75 g_signal_emit_valist (libgobject-2.0.so.0 + 0x31f75)
                                               #27 0x00007fd846541204 g_signal_emit (libgobject-2.0.so.0 + 0x32204)
                                               #28 0x00007fd845e88596 n/a (libgtk-x11-2.0.so.0 + 0x88596)
                                               #29 0x00007fd846523210 g_closure_invoke (libgobject-2.0.so.0 + 0x14210)
                                               #30 0x00007fd846550b47 n/a (libgobject-2.0.so.0 + 0x41b47)
                                               #31 0x00007fd846540f75 g_signal_emit_valist (libgobject-2.0.so.0 + 0x31f75)
                                               #32 0x00007fd846541204 g_signal_emit (libgobject-2.0.so.0 + 0x32204)
                                               #33 0x00007fd845e8746a n/a (libgtk-x11-2.0.so.0 + 0x8746a)
                                               #34 0x00007fd845f360a8 n/a (libgtk-x11-2.0.so.0 + 0x1360a8)
                                               #35 0x00007fd846523210 g_closure_invoke (libgobject-2.0.so.0 + 0x14210)
                                               #36 0x00007fd846550fd7 n/a (libgobject-2.0.so.0 + 0x41fd7)
                                               #37 0x00007fd846540980 g_signal_emit_valist (libgobject-2.0.so.0 + 0x31980)
                                               #38 0x00007fd846541204 g_signal_emit (libgobject-2.0.so.0 + 0x32204)
                                               #39 0x00007fd84605b275 n/a (libgtk-x11-2.0.so.0 + 0x25b275)
                                               #40 0x00007fd845f346d6 gtk_propagate_event (libgtk-x11-2.0.so.0 + 0x1346d6)
                                               #41 0x00007fd845f34b4b gtk_main_do_event (libgtk-x11-2.0.so.0 + 0x134b4b)
                                               #42 0x00007fd8463733be n/a (libgdk-x11-2.0.so.0 + 0x5e3be)
                                               #43 0x00007fd84642587b g_main_context_dispatch (libglib-2.0.so.0 + 0x5587b)
                                               #44 0x00007fd84647cc89 n/a (libglib-2.0.so.0 + 0xacc89)
                                               #45 0x00007fd846424ddf g_main_loop_run (libglib-2.0.so.0 + 0x54ddf)
                                               #46 0x00007fd845f339fe gtk_main (libgtk-x11-2.0.so.0 + 0x1339fe)
                                               #47 0x00007fd846750d29 _ZN9Gtkmm2ext2UI3runER8Receiver (libgtkmm2ext.so.0 + 0x57d29)
                                               #48 0x0000558eb93ff666 main (ardour-7.2.0 + 0x489666)
                                               #49 0x00007fd844a5a290 n/a (libc.so.6 + 0x23290)
                                               #50 0x00007fd844a5a34a __libc_start_main (libc.so.6 + 0x2334a)
                                               #51 0x0000558eb9409965 n/a (ardour-7.2.0 + 0x493965)
                                               
                                               Stack trace of thread 5319:
                                               #0  0x00007fd844b377fd syscall (libc.so.6 + 0x1007fd)
                                               #1  0x00007fd846475e15 g_cond_wait (libglib-2.0.so.0 + 0xa5e15)
                                               #2  0x00007fd846d579d9 _ZN6ARDOUR8Analyser4workEv (libardour.so.3 + 0x3579d9)
                                               #3  0x00007fd8466c00aa _ZN3PBD6Thread4_runEPv (libpbd.so.4 + 0x400aa)
                                               #4  0x00007fd844abd8fd n/a (libc.so.6 + 0x868fd)
                                               #5  0x00007fd844b3fa60 n/a (libc.so.6 + 0x108a60)
                                               
                                               Stack trace of thread 5321:
                                               #0  0x00007fd844b377fd syscall (libc.so.6 + 0x1007fd)
                                               #1  0x00007fd846475e15 g_cond_wait (libglib-2.0.so.0 + 0xa5e15)
                                               #2  0x00007fd846d79bd1 _ZN6ARDOUR11AudioEngine16do_reset_backendEv (libardour.so.3 + 0x379bd1)
                                               #3  0x00007fd8466c00aa _ZN3PBD6Thread4_runEPv (libpbd.so.4 + 0x400aa)
                                               #4  0x00007fd844abd8fd n/a (libc.so.6 + 0x868fd)
                                               #5  0x00007fd844b3fa60 n/a (libc.so.6 + 0x108a60)
                                               
                                               Stack trace of thread 5315:
                                               #0  0x00007fd844b320bf __poll (libc.so.6 + 0xfb0bf)
                                               #1  0x00007fd8466ac78d _ZN18CrossThreadChannel16poll_for_requestEv (libpbd.so.4 + 0x2c78d)
                                               #2  0x00007fd8466ac813 _ZN18CrossThreadChannel7receiveERcb (libpbd.so.4 + 0x2c813)
                                               #3  0x00007fd84726bb42 _ZN6ARDOUR16TriggerBoxThread11thread_workEv (libardour.so.3 + 0x86bb42)
                                               #4  0x00007fd8466bfffa n/a (libpbd.so.4 + 0x3fffa)
                                               #5  0x00007fd844abd8fd n/a (libc.so.6 + 0x868fd)
                                               #6  0x00007fd844b3fa60 n/a (libc.so.6 + 0x108a60)
                                               
                                               Stack trace of thread 5449:
                                               #0  0x00007fd844b3f096 epoll_wait (libc.so.6 + 0x108096)
                                               #1  0x00007fd8466758a9 n/a (libspa-support.so + 0x158a9)
                                               #2  0x00007fd8466669db n/a (libspa-support.so + 0x69db)
                                               #3  0x00007fd842d737d6 pw_data_loop_wait (libpipewire-0.3.so.0 + 0x3d7d6)
                                               #4  0x00007fd842e21670 jack_cycle_wait (libjack.so.0 + 0x18670)
                                               #5  0x00007fd83c1e6554 _ZN6ARDOUR16JACKAudioBackend14process_threadEv (libjack_audiobackend.so + 0x19554)
                                               #6  0x00007fd846666b27 n/a (libspa-support.so + 0x6b27)
                                               #7  0x00007fd842d78df7 n/a (libpipewire-0.3.so.0 + 0x42df7)
                                               #8  0x00007fd844abd8fd n/a (libc.so.6 + 0x868fd)
                                               #9  0x00007fd844b3fa60 n/a (libc.so.6 + 0x108a60)
                                               
                                               Stack trace of thread 5318:
                                               #0  0x00007fd844b377fd syscall (libc.so.6 + 0x1007fd)
                                               #1  0x00007fd846475e15 g_cond_wait (libglib-2.0.so.0 + 0xa5e15)
                                               #2  0x00007fd84722bf9c n/a (libardour.so.3 + 0x82bf9c)
                                               #3  0x00007fd8466c00aa _ZN3PBD6Thread4_runEPv (libpbd.so.4 + 0x400aa)
                                               #4  0x00007fd844abd8fd n/a (libc.so.6 + 0x868fd)
                                               #5  0x00007fd844b3fa60 n/a (libc.so.6 + 0x108a60)
                                               
                                               Stack trace of thread 5316:
                                               #0  0x00007fd844b047c5 clock_nanosleep (libc.so.6 + 0xcd7c5)
                                               #1  0x00007fd844b092d7 __nanosleep (libc.so.6 + 0xd22d7)
                                               #2  0x00007fd8464504e1 g_usleep (libglib-2.0.so.0 + 0x804e1)
                                               #3  0x0000558eb9bf4327 n/a (ardour-7.2.0 + 0xc7e327)
                                               #4  0x00007fd844abd8fd n/a (libc.so.6 + 0x868fd)
                                               #5  0x00007fd844b3fa60 n/a (libc.so.6 + 0x108a60)
                                               
                                               Stack trace of thread 5354:
                                               #0  0x00007fd844b320bf __poll (libc.so.6 + 0xfb0bf)
                                               #1  0x00007fd84647cbef n/a (libglib-2.0.so.0 + 0xacbef)
                                               #2  0x00007fd846424ddf g_main_loop_run (libglib-2.0.so.0 + 0x54ddf)
                                               #3  0x00007fd8441bdadc n/a (libgio-2.0.so.0 + 0x10aadc)
                                               #4  0x00007fd846452e05 n/a (libglib-2.0.so.0 + 0x82e05)
                                               #5  0x00007fd844abd8fd n/a (libc.so.6 + 0x868fd)
                                               #6  0x00007fd844b3fa60 n/a (libc.so.6 + 0x108a60)
                                               
                                               Stack trace of thread 5448:
                                               #0  0x00007fd844b3f096 epoll_wait (libc.so.6 + 0x108096)
                                               #1  0x00007fd8466758a9 n/a (libspa-support.so + 0x158a9)
                                               #2  0x00007fd8466669db n/a (libspa-support.so + 0x69db)
                                               #3  0x00007fd842db874a n/a (libpipewire-0.3.so.0 + 0x8274a)
                                               #4  0x00007fd844abd8fd n/a (libc.so.6 + 0x868fd)
                                               #5  0x00007fd844b3fa60 n/a (libc.so.6 + 0x108a60)
                                               
                                               Stack trace of thread 5317:
                                               #0  0x00007fd844b377fd syscall (libc.so.6 + 0x1007fd)
                                               #1  0x00007fd846475e15 g_cond_wait (libglib-2.0.so.0 + 0xa5e15)
                                               #2  0x00007fd84722bf9c n/a (libardour.so.3 + 0x82bf9c)
                                               #3  0x00007fd8466c00aa _ZN3PBD6Thread4_runEPv (libpbd.so.4 + 0x400aa)
                                               #4  0x00007fd844abd8fd n/a (libc.so.6 + 0x868fd)
                                               #5  0x00007fd844b3fa60 n/a (libc.so.6 + 0x108a60)
                                               
                                               Stack trace of thread 5353:
                                               #0  0x00007fd844b320bf __poll (libc.so.6 + 0xfb0bf)
                                               #1  0x00007fd84647cbef n/a (libglib-2.0.so.0 + 0xacbef)
                                               #2  0x00007fd846424132 g_main_context_iteration (libglib-2.0.so.0 + 0x54132)
                                               #3  0x00007fd846424182 n/a (libglib-2.0.so.0 + 0x54182)
                                               #4  0x00007fd846452e05 n/a (libglib-2.0.so.0 + 0x82e05)
                                               #5  0x00007fd844abd8fd n/a (libc.so.6 + 0x868fd)
                                               #6  0x00007fd844b3fa60 n/a (libc.so.6 + 0x108a60)
                                               
                                               Stack trace of thread 5322:
                                               #0  0x00007fd844b377fd syscall (libc.so.6 + 0x1007fd)
                                               #1  0x00007fd846475e15 g_cond_wait (libglib-2.0.so.0 + 0xa5e15)
                                               #2  0x00007fd846d7884c _ZN6ARDOUR11AudioEngine20do_devicelist_updateEv (libardour.so.3 + 0x37884c)
                                               #3  0x00007fd8466c00aa _ZN3PBD6Thread4_runEPv (libpbd.so.4 + 0x400aa)
                                               #4  0x00007fd844abd8fd n/a (libc.so.6 + 0x868fd)
                                               #5  0x00007fd844b3fa60 n/a (libc.so.6 + 0x108a60)
                                               ELF object binary architecture: AMD x86-64
```

**Comment by michaellass** [comment]
Build with `-O0 -g` gives the following output in gdb:

```
Thread 1 "ArdourGUI" received signal SIGSEGV, Segmentation fault.
0x00007fffe82a6845 in init () at notch_harmonics.c:169
169	  descriptor = (LADSPA_Descriptor *)malloc(sizeof(LADSPA_Descriptor));
(gdb) bt
#0  0x00007fffe82a6845 in init () at notch_harmonics.c:169
#1  0x00007ffff7fcecee in call_init (env=0x7fffffffdc78, argv=0x7fffffffdc68, argc=1, l=<optimized out>) at dl-init.c:70
#2  call_init (l=<optimized out>, argc=1, argv=0x7fffffffdc68, env=0x7fffffffdc78) at dl-init.c:26
#3  0x00007ffff7fceddc in _dl_init (main_map=0x55555755f6e0, argc=1, argv=0x7fffffffdc68, env=0x7fffffffdc78) at dl-init.c:117
#4  0x00007ffff5586e94 in __GI__dl_catch_exception (exception=<optimized out>, operate=<optimized out>, args=<optimized out>) at /usr/src/debug/glibc/elf/dl-error-skeleton.c:182
#5  0x00007ffff7fd5557 in dl_open_worker (a=a@entry=0x7fffffffbf30) at dl-open.c:808
#6  0x00007ffff5586e3e in __GI__dl_catch_exception (exception=<optimized out>, operate=<optimized out>, args=<optimized out>) at /usr/src/debug/glibc/elf/dl-error-skeleton.c:208
#7  0x00007ffff7fd58ed in _dl_open (file=0x555556cf7b30 "/usr/local/lib/ladspa/notch_harmonics_5761.so", mode=<optimized out>, caller_dlopen=0x7ffff6458782 <g_module_open_full+578>, nsid=<optimized out>, argc=1, argv=0x7fffffffdc68, env=0x7fffffffdc78) at dl-open.c:886
#8  0x00007ffff54b99dc in dlopen_doit (a=a@entry=0x7fffffffc1a0) at dlopen.c:56
#9  0x00007ffff5586e3e in __GI__dl_catch_exception (exception=exception@entry=0x7fffffffc100, operate=<optimized out>, args=<optimized out>) at /usr/src/debug/glibc/elf/dl-error-skeleton.c:208
#10 0x00007ffff5586ef3 in __GI__dl_catch_error (objname=0x7fffffffc158, errstring=0x7fffffffc160, mallocedp=0x7fffffffc157, operate=<optimized out>, args=<optimized out>) at /usr/src/debug/glibc/elf/dl-error-skeleton.c:227
#11 0x00007ffff54b94af in _dlerror_run (operate=operate@entry=0x7ffff54b9980 <dlopen_doit>, args=args@entry=0x7fffffffc1a0) at dlerror.c:138
#12 0x00007ffff54b9a91 in dlopen_implementation (dl_caller=<optimized out>, mode=<optimized out>, file=<optimized out>) at dlopen.c:71
#13 ___dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:81
#14 0x00007ffff6458782 in _g_module_open (error=0x0, bind_local=<optimized out>, bind_lazy=0, file_name=0x555556cf7b30 "/usr/local/lib/ladspa/notch_harmonics_5761.so") at ../glib/gmodule/gmodule-dl.c:138
#15 g_module_open_full (file_name=0x555556c770c0 "/usr/local/lib/ladspa/notch_harmonics_5761.so", flags=<optimized out>, error=0x0) at ../glib/gmodule/gmodule.c:614
#16 0x00007ffff6f34434 in Glib::Module::Module(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Glib::ModuleFlags)
    (this=this@entry=0x7fffffffc320, file_name="/usr/local/lib/ladspa/notch_harmonics_5761.so", flags=flags@entry=0, this=<optimized out>, file_name=<optimized out>, flags=<optimized out>) at glib/glibmm/module.cc:33
#17 0x00007ffff78cae97 in ARDOUR::PluginManager::ladspa_discover(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (this=0x55555675c940, path="/usr/local/lib/ladspa/notch_harmonics_5761.so") at ../libs/ardour/plugin_manager.cc:886
#18 0x00007ffff78cc3f6 in ARDOUR::PluginManager::ladspa_refresh() (this=0x55555675c940) at ../libs/ardour/plugin_manager.cc:801
#19 0x00007ffff78cc738 in ARDOUR::PluginManager::refresh(bool) (this=0x55555675c940, cache_only=<optimized out>) at ../libs/ardour/plugin_manager.cc:466
#20 0x00005555560f552a in PluginScanDialog::start() (this=0x5555573e9670) at ../gtk2_ardour/plugin_scan_dialog.cc:176
#21 StartupFSM::show_plugin_scan_dialog() (this=0x555556f7cca0) at ../gtk2_ardour/startup_fsm.cc:404
#22 StartupFSM::engine_running() (this=0x555556f7cca0) at ../gtk2_ardour/startup_fsm.cc:533
#23 0x00005555560f5840 in StartupFSM::start_audio_midi_setup() (this=0x555556f7cca0) at ../gtk2_ardour/startup_fsm.cc:523
#24 0x00007ffff6278e79 in  () at /usr/lib/libgtkmm-2.4.so.1
#25 0x00007ffff6ea4210 in g_closure_invoke (closure=0x5555573313d0, return_value=0x0, n_param_values=2, param_values=0x7fffffffcd70, invocation_hint=0x7fffffffccf0) at ../glib/gobject/gclosure.c:832
#26 0x00007ffff6ed2176 in signal_emit_unlocked_R.isra.0 (node=node@entry=0x555556dc1f20, detail=detail@entry=0, instance=instance@entry=0x555556edb2f0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffcd70)
    at ../glib/gobject/gsignal.c:3867
#27 0x00007ffff6ec1f75 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffcf30) at ../glib/gobject/gsignal.c:3549
#28 0x00007ffff6ec2204 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../glib/gobject/gsignal.c:3606
#29 0x000055555609549f in SessionDialog::open_button_pressed(_GdkEventButton*) (this=0x555556c72400, ev=<optimized out>) at ../gtk2_ardour/session_dialog.cc:543
#30 0x00007ffff630152f in  () at /usr/lib/libgtkmm-2.4.so.1
#31 0x00007ffff69360a8 in  () at /usr/lib/libgtk-x11-2.0.so.0
#32 0x00007ffff6ea4210 in g_closure_invoke (closure=0x555556d2db90, return_value=0x7fffffffd1b0, n_param_values=2, param_values=0x7fffffffd210, invocation_hint=0x7fffffffd190) at ../glib/gobject/gclosure.c:832
#33 0x00007ffff6ed1ea8 in signal_emit_unlocked_R.isra.0 (node=<optimized out>, detail=detail@entry=0, instance=instance@entry=0x55555734ee50, emission_return=emission_return@entry=0x7fffffffd320, instance_and_params=instance_and_params@entry=0x7fffffffd210)
    at ../glib/gobject/gsignal.c:3796
#34 0x00007ffff6ec1980 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd3d0) at ../glib/gobject/gsignal.c:3559
#35 0x00007ffff6ec2204 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../glib/gobject/gsignal.c:3606
#36 0x00007ffff6a5b275 in  () at /usr/lib/libgtk-x11-2.0.so.0
#37 0x00007ffff69346d6 in gtk_propagate_event () at /usr/lib/libgtk-x11-2.0.so.0
#38 0x00007ffff6934b4b in gtk_main_do_event () at /usr/lib/libgtk-x11-2.0.so.0
#39 0x00007ffff6cf43be in  () at /usr/lib/libgdk-x11-2.0.so.0
#40 0x00007ffff6da687b in g_main_dispatch (context=0x55555705cc10) at ../glib/glib/gmain.c:3454
#41 g_main_context_dispatch (context=0x55555705cc10) at ../glib/glib/gmain.c:4172
#42 0x00007ffff6dfdc89 in g_main_context_iterate.constprop.0 (context=0x55555705cc10, block=1, dispatch=1, self=<optimized out>) at ../glib/glib/gmain.c:4248
#43 0x00007ffff6da5ddf in g_main_loop_run (loop=0x55555737df80) at ../glib/glib/gmain.c:4448
#44 0x00007ffff69339fe in gtk_main () at /usr/lib/libgtk-x11-2.0.so.0
#45 0x00007ffff70d1d29 in Gtkmm2ext::UI::run(Receiver&) (this=this@entry=0x555556d5af80, old_receiver=...) at ../libs/gtkmm2ext/gtk_ui.cc:309
#46 0x00005555559dd666 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at ../gtk2_ardour/main.cc:456
```
